
CREATE DATABASE Senai_Hroads_Tarde
GO 

USE SENAI_HROADS_TARDE
GO


CREATE TABLE CLASSE(
	idClasse INT PRIMARY KEY IDENTITY,
	nomeClasse VARCHAR(15)
);
GO

CREATE TABLE PERSONAGEM(
	idPersonagem INT PRIMARY KEY IDENTITY,
	idClasse INT FOREIGN KEY REFERENCES CLASSE(idClasse),
	nomePersonagem VARCHAR(20),
	capMana TINYINT,
	capVida TINYINT,
	dataAtt DATE,
	dataCriacao DATE
);
GO


CREATE TABLE HABILIDADE(
	idHabilidade INT PRIMARY KEY IDENTITY,
	idClasse INT FOREIGN KEY REFERENCES CLASSE(idClasse),
	nomeHabilidade VARCHAR(15)
);
GO


CREATE TABLE CLASSE_HABILIDADE(
	idCasseHabilidade INT PRIMARY KEY IDENTITY,
	idHabilidade INT FOREIGN KEY REFERENCES HABILIDADE(idHabilidade),
	idClasse INT FOREIGN KEY REFERENCES CLASSE(idClasse),
);
GO


CREATE TABLE TIPO_H(
	idTipoH INT PRIMARY KEY IDENTITY,
	idHabilidade INT FOREIGN KEY REFERENCES HABILIDADE(idHabilidade),
	nomeTipoH VARCHAR(15)
);
GO

 
   