
CREATE DATABASE Senai_Hroads_Tarde
GO 

USE SENAI_HROADS_TARDE
GO


CREATE TABLE CLASSE(
	idClasse SMALLINT PRIMARY KEY IDENTITY,
	nomeClasse VARCHAR(50)
);
GO

CREATE TABLE TIPO_H(
	idTipoH SMALLINT PRIMARY KEY IDENTITY,
	nomeTipoH VARCHAR(50)
);
GO

CREATE TABLE PERSONAGEM(
	idPersonagem SMALLINT PRIMARY KEY IDENTITY,
	idClasse SMALLINT FOREIGN KEY REFERENCES CLASSE(idClasse),
	nomePersonagem VARCHAR(50),
	capMana TINYINT,
	capVida TINYINT,
	dataAtt DATE,
	dataCriacao DATE
);
GO


CREATE TABLE HABILIDADE(
	idHabilidade SMALLINT PRIMARY KEY IDENTITY,
	idTipoH SMALLINT FOREIGN KEY REFERENCES CLASSE(idClasse),
	nomeHabilidade VARCHAR(50)
);
GO


CREATE TABLE CLASSE_HABILIDADE(
	idClasseHabilidade SMALLINT PRIMARY KEY IDENTITY,
	idHabilidade SMALLINT FOREIGN KEY REFERENCES HABILIDADE(idHabilidade),
	idClasse SMALLINT FOREIGN KEY REFERENCES CLASSE(idClasse),
);
GO